### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by liuyiyi2016** [Aufree/ESTMusicIndicator#3]
Hello!
   Your program is very well done. Thanks very much for you sharing,but I found a problem in the test.
   In this program you have set up ten rows of data,and it works well.But if I set up more rows of data,for example eighty rows, when it works,I click on the first line，I find the first line,the fifteenth line ，the twenty-ninth line，the forty-third line，the fifty-seventh line and the seventy-first line indicators are all Animating. This is wrong,Please help!

**Comment by yarodevuci** [comment]
Hello. Did you solve the problem?
I have the same issue but I solved it by different approach
Let me know if you need help

**Comment by Aufree** [comment]
[Fixed!](https://github.com/Aufree/ESTMusicIndicator/commit/759d407039e723b5a388ab7af4674e82819266e2)
