### ISSUE TITLE
Swift 3?

### ISSUE THREAD

**Issue by Glaubenio** [Aufree/ESTMusicIndicator#5]
Is there a way to use it with swift 3?

**Comment by yarodevuci** [comment]
What problem do you have? I am using it on swift 3 without any problems 
Just let XCode to convert it for you

**Comment by davidseek** [comment]
+1

and i don't let xcode convert frameworks...

**Comment by mxcl** [comment]
This guy ported it: https://github.com/davidseek/ESTMusicIndicator

You can update your Podfile to use his fork.

Never come here again since apparently @Aufree doesn't give a shit.

**Comment by yarodevuci** [comment]
Lol ,I agree

**Comment by davidseek** [comment]
`pod 'ESTMusicIndicator', :git => 'https://github.com/davidseek/ESTMusicIndicator.git'`

well. he might just have too much stuff to do... he has 10k stars in other projects...
hope my fork helps you guys

**Comment by mxcl** [comment]
I have way more and keep my stuff up to date. Publishing implies commitment.

**Comment by Aufree** [comment]
@Glaubenio @yarodevuci @mxcl @yarodevuci Sorry guys, too much trivia recently, @davidseek providing a [solution](https://github.com/davidseek/ESTMusicIndicator/commit/691f772363830ed2ebebbcdee1457c6ab94f758c) for this, I will update this project after a few days later.

**Comment by davidseek** [comment]
@Aufree Feel free to use my solution

**Comment by Aufree** [comment]
@davidseek Thank you.

**Comment by Aufree** [comment]
This repo has been upgrade to Swfit 3.0, Enjoy~ 🎉  🎉  🎉 

![image](https://cloud.githubusercontent.com/assets/5310542/22100951/3ce4f61e-de6c-11e6-8679-e1efdfb73088.png)
